//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SmallHorse.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDR_MAINFRAME                   128
#define IDR_RECORD_MENU                 130
#define IDR_POPUP_TOOLBAR               131
#define IDB_BOOK                        133
#define IDI_ICON1                       134
#define IDD_ADDRECORD                   136
#define IDD_ADDNEWBANKBOOK              138
#define IDD_PASSWORD                    144
#define IDB_WORKSPACE                   147
#define IDR_TREEMENU                    147
#define IDB_TOOLBAR256                  151
#define IDB_TOOLBARCOLD256              152
#define IDR_HISTORY_POPUP               154
#define IDD_QUERYEND                    154
#define IDB_TASKS                       160
#define IDR_BANKBOOK_MENU               162
#define IDR_SUBCOUNT_MENU               163
#define IDB_TESTONLY                    165
#define IDR_MENU_QUERY                  166
#define IDD_ENTRY                       168
#define IDC_NULL                        168
#define IDD_QUERY_FROM_DATE             169
#define IDD_S1                          171
#define IDD_S2                          172
#define IDD_S3                          173
#define IDD_IMPORT2                     175
#define IDD_IMPORT1                     176
#define IDD_SET_RECORD_TYPE             177
#define IDD_PERIOD_SETUP                178
#define IDD_CHECKMONTHVALUE             179
#define IDD_FINDBOOK_SETUP              180
#define IDD_DINGQI_SAVE                 181
#define IDD_S5                          182
#define IDD_ADDCREDITCARD               183
#define IDD_QUERY_FROM_MONEY            184
#define IDB_INACTIVE                    185
#define IDD_QUERY_FROM_COMMENT          185
#define IDB_ACTIVE                      186
#define IDD_CLOSE_SUBCOUNT              189
#define IDR_MENU_COMPARE                190
#define IDR_SUBCOUNT_MANAGER_MENU       191
#define IDD_COPY_RECORDS                195
#define IDD_REPLACE_STRING              196
#define IDB_LIST_IMAGES                 197
#define IDD_DINGQI_MANAGER_DIALOG       197
#define IDC_EDIT_MONEY_RANGE            1000
#define IDC_EDIT_MONEY                  1001
#define IDC_DATETIMEPICKER              1002
#define IDC_EDIT_RATE                   1003
#define IDC_DATETIMEPICKER_END          1004
#define IDC_NEWID                       1011
#define IDC_NEWNAME                     1012
#define IDC_NEWBANK                     1013
#define IDC_NEWCOMIT                    1014
#define IDC_BOOK_TYPE                   1015
#define IDC_EDIT_ID                     1015
#define IDC_EDIT_SUBCOUNT               1016
#define IDC_NEWCARD                     1016
#define IDC_NEXTINPUT                   1017
#define IDC_EDIT_MAINCOUNT              1017
#define IDC_EDIT_OWNER                  1017
#define IDC_EDIT_PASSWORD               1018
#define IDC_ID                          1019
#define IDC_LIST                        1022
#define IDC_REMAIN                      1023
#define IDC_EDIT_PWD                    1024
#define IDC_EDIT_USER                   1025
#define IDC_COMBO_TYPE                  1029
#define IDC_COMBO_SITE                  1030
#define IDC_LIST_TARGET_NAME            1032
#define IDC_CHECK_ALLDATE               1032
#define IDC_LIST_SRC_TYPE               1032
#define IDC_DATETIMEPICKER1             1033
#define IDC_DATETIMEPICKER2             1034
#define IDC_LIST_SRC_NAME               1035
#define IDC_DATETIME_END                1036
#define IDC_LIST_TARGET_TYPE            1036
#define IDC_DATETIME_PAY                1037
#define IDC_EDIT_FIND_STRING            1037
#define IDC_EDIT_FILE                   1037
#define IDC_SELECTFILE                  1038
#define IDC_LIST_DATA                   1039
#define IDC_MARKALL                     1040
#define IDC_COMPANY_URL                 1041
#define IDC_UNMARKALL                   1041
#define IDC_MARKSELED                   1042
#define IDC_UNMARKSELECTED              1043
#define IDC_EDIT_MUST_HAVE              1044
#define IDC_EDIT_HAVE_NOT               1045
#define IDC_DATETIME_BEGIN              1046
#define IDC_EDIT_SITE                   1046
#define IDC_COMBO_DATE_END              1047
#define IDC_SAVE_RESULT                 1048
#define IDC_COMBO_DATE_PAY              1048
#define ID_LIST_ID_SET                  1049
#define ID_EDIT_ID_SET                  1050
#define IDC_COMBO_SUB_COUNT             1054
#define IDC_COMBO_TIMESPAN              1054
#define IDC_COMMENT                     1055
#define IDC_EDIT_GREAT                  1055
#define IDC_RADIO_TRANSFER              1056
#define IDC_RADIO_NEW_SAVE              1057
#define IDC_EDIT_STATEMENT_DATE         1060
#define IDC_EDIT_PAY_DATE               1061
#define IDC_MONTHCALENDAR               1063
#define IDC_EDIT_DATE_BOUND             1064
#define IDC_SPIN                        1065
#define IDC_EDIT_INFO                   1066
#define IDC_SPIN2                       1068
#define IDC_EDIT_SMALL                  1069
#define IDC_CHECK_GREAT                 1070
#define IDC_CHECK_SMALL                 1071
#define IDC_RADIO_AND                   1072
#define IDC_RADIO_OR                    1073
#define IDC_EDIT_COMMENT                1073
#define IDC_RADIO_RANGE_FREE            1076
#define IDC_RADIO_RANGE_SIMPLE          1077
#define IDC_EDIT_EQUAL                  1081
#define IDC_CHECK_SAVETO_DEFAULT        1083
#define IDC_BUTTON_NEXT_MONTH           1085
#define IDC_BUTTON_PREV_MONTH           1086
#define IDC_ADD_DEFAULT_NOTE            1087
#define IDC_CHECK_TYPE                  1088
#define IDC_CHECK_SITE                  1089
#define IDC_CHECK_TRANSFER              1091
#define IDC_EDIT_OLD_STR                1092
#define IDC_EDIT_NEW_STR                1093
#define IDC_EDIT_BANK                   1094
#define IDC_DATETIMEPICKER_START        1095
#define IDM_COPY_RECORDS_TO             32000
#define IDM_COPY_RECORDS_TO_END         32010
#define IDM_MOVE_RECORDS_TO             32020
#define IDM_MOVE_RECORDS_TO_END         32040
#define ID_VIEW_CUSTOMIZE               32770
#define IDM_INFO                        32787
#define IDM_DELETEBOOK                  32788
#define IDM_RECTIFYINFO                 32790
#define IDM_RECTIFYPASSWORD             32791
#define ID_VIEW_WORKSPACE2              32792
#define ID_VIEW_USER_TOOLBAR1           32793
#define ID_VIEW_USER_TOOLBAR2           32794
#define ID_VIEW_USER_TOOLBAR3           32795
#define ID_VIEW_USER_TOOLBAR4           32796
#define ID_VIEW_USER_TOOLBAR5           32797
#define ID_VIEW_USER_TOOLBAR6           32798
#define ID_VIEW_USER_TOOLBAR7           32799
#define ID_VIEW_USER_TOOLBAR8           32800
#define ID_VIEW_USER_TOOLBAR9           32801
#define ID_VIEW_USER_TOOLBAR10          32802
#define ID_VIEW_WORKSPACE               32803
#define ID_VIEW_OUTPUT                  32804
#define ID_RECORD_MODIFY                32806
#define ID_QUERY                        32808
#define ID_BANKBOOK_FREE                32810
#define ID_VIEW_FOLDERS                 32822
#define ID_CAL_CREDIT                   32822
#define ID_FOLDER_UP                    32823
#define ID_ADD_RETURN_RECORD            32824
#define ID_EDIT_SMART_TYPE              32825
#define ID_VIEW_APPLOOK_2000            32826
#define ID_MOVE_TO                      32826
#define ID_SET_AS_AUTORETURN_CREDIT     32826
#define ID_VIEW_APPLOOK_XP              32827
#define ID_COPY_TO                      32827
#define ID_VIEW_TASKPANE                32827
#define ID_VIEW_APPLOOK_2003            32828
#define ID_VIEW_VIEWS                   32828
#define ID_FIND_BOOK                    32828
#define ID_VIEW_APPLOOK_WIN_XP          32829
#define ID_COMMAND_HISTORY              32829
#define ID_VIEW_APPLOOK_VS2005          32830
#define ID_VIEW_APPLOOK_2007            32831
#define ID_FILE_MRU_QUERY0              32850
#define ID_FILE_MRU_QUERY1              32851
#define ID_FILE_MRU_QUERY2              32852
#define ID_FILE_MRU_QUERY3              32853
#define ID_FILE_MRU_QUERY4              32854
#define ID_FILE_MRU_QUERY5              32855
#define ID_FILE_MRU_QUERY6              32856
#define ID_FILE_MRU_QUERY7              32857
#define ID_FILE_MRU_QUERY8              32858
#define ID_FILE_MRU_QUERY9              32859
#define ID_FILE_MRU_QUERY10             32860
#define ID_FILE_MRU_QUERY11             32861
#define ID_FILE_MRU_QUERY12             32862
#define ID_FILE_MRU_QUERY13             32863
#define ID_FILE_MRU_QUERY14             32864
#define ID_FILE_MRU_QUERY15             32865
#define ID_TRANSFER_DINGQI              32867
#define IDM_MODIFY_SUBCOUNT             32874
#define IDM_RENEW_SUBCOUNT              32875
#define ID_OPEN_SUBCOUNT_BY_ID          32876
#define ID_ADD_CREDIT_PAY_INFO          32878
#define ID_QUERY_MONEY                  32880
#define ID_QUERY_COMMENT                32881
#define ID_QUERY_DATE                   32882
#define ID_SUBCOUNT_CLOSE               32883
#define ID_EXPAND_ACTIVE_ITEM           32884
#define ID_EXPAND_ALL_ITEM              32885
#define ID_COLLAPSE_ALL_ITEM            32886
#define ID_COLLAPSE_INACTIVE_INACTIVE   32887
#define ID_COMPARE_MERGE                32889
#define ID_COMPARE_DELETE               32890
#define ID_CHECK_BILL                   32892
#define ID_COMPARE_COPY_TO_RIGHT        32893
#define ID_COMPARE_COPY_TO_LEFT         32894
#define ID_COMPARE_SAVE                 32896
#define ID_MENU_CREDIT_REPORT           32898
#define ID_COMAPRE_JOIN                 32899
#define ID_COUNT_LOCK                   32900
#define ID_THIS_YEAR                    32901
#define ID_THIS_YEAR_1                  32902
#define ID_THIS_YEAR_2                  32903
#define ID_THIS_YEAR_3                  32904
#define ID_THIS_YEAR_4                  32905
#define ID_THIS_YEAR_5                  32906
#define ID_THIS_YEAR_6                  32907
#define ID_THIS_YEAR_7                  32908
#define ID_DATABASE_BACKUP              32909
#define ID_DATABASE_COMPARE             32910
#define ID_IDR_IDR                      32924
#define ID_DATABASE_MODIFY_PWD          32925
#define ID_ACCOUNT_NEW                  32926
#define ID_RECORD_NEW                   32927
#define ID_DELETE_SEL_RECORD            32928
#define ID_RECORD_IMPORT                32929
#define ID_RECORD_EXPORT                32930
#define ID_RECORD_DEL_SELECTED          32931
#define ID_SUBCOUNT_EXPAND_ALL          32932
#define ID_SUBCOUNT_EXPAND_DEFAULT      32933
#define ID_SUBCOUNT_SHRINK_ALL          32934
#define ID_SUBCOUNT_EXPAND_ACTIVE       32935
#define ID_SUBCOUNT_SHRINK_CLOSED       32936
#define ID_EDIT_CAL_SUM                 32938
#define ID_ACCOUNT_SHOW_CLOSED          32941
#define ID_ACCOUNT                      32942
#define ID_SUBCOUNT_LIST_DETAIL_ALL     32943
#define ID_SUBCOUNT_LIST_ALL            32944
#define ID_RECORD_COPY                  32949
#define ID_RECORD_PASTE                 32950
#define ID_EDIT_REPLACE_COMMENT         32954
#define ID_EDIT_TEST                    32955
#define ID_EDIT_CREDIT_PERIOD           32956
#define ID_BOOK_DOUNT_STATIC            32958
#define ID_QUERY_ONE_DAY                32960
#define ID_RECORD_MOVE                  32962
#define ID_TODO                         32963
#define ID_SEARCH_DATETIME_MAIN         32964
#define ID_SEARCH_DAY_ROUND             32966
#define ID_SEARCH_QUERY                 32969

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         32971
#define _APS_NEXT_CONTROL_VALUE         1096
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
